# Generated by Django 5.1 on 2024-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_epi'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='status',
            field=models.CharField(default='disponível', max_length=20),
        ),
    ]
